name: Build and Push Docker Image
description: Build and push multi-arch Docker images with cache and metadata

inputs:
  image_name:
    description: Docker image name (without registry)
    required: true

  dockerfile:
    description: Path to Dockerfile
    required: false
    default: Dockerfile

  context:
    description: Build context
    required: false
    default: .

  target:
    description: Docker build target
    required: false
    default: prod

  platforms:
    description: Build platforms
    required: false
    default: linux/amd64,linux/arm64

  push_latest:
    description: Push latest tag
    required: false
    default: "true"

  docker_registry:
    description: Docker registry URL
    required: true

  docker_username:
    description: Docker registry username
    required: true

  docker_token:
    description: Docker registry token/password
    required: true

  build_args:
    description: Docker build arguments
    required: false
    default: ""

  ci_trigger_token:
    description: Token to trigger docker-repo build
    required: false
    default: ""

  repository_trigger:
    description: Repository to trigger after build
    required: false
    default: RedirectorPlatform/Docker

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.docker_registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=latest,enable=${{ inputs.push_latest }}
          type=sha
          type=ref,event=branch
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}

    # Build WITH target
    - name: Build and push Docker image (with target)
      if: ${{ inputs.target != '' }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        cache-from: |
          type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}:buildcache
        cache-to: |
          type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}:buildcache,mode=max

    # Build WITHOUT target
    - name: Build and push Docker image (no target)
      if: ${{ inputs.target == '' }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile }}
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        cache-from: |
          type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}:buildcache
        cache-to: |
          type=registry,ref=${{ inputs.docker_registry }}/${{ inputs.image_name }}:buildcache,mode=max

    - name: Trigger docker repo build
      if: ${{ inputs.ci_trigger_token != '' && inputs.repository_trigger != '' }}
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.ci_trigger_token }}
        repository: ${{ inputs.repository_trigger }}
        event-type: user-service-built
        client-payload: |
          {
            "service": "${{ inputs.image_name }}",
            "sha": "${{ github.sha }}"
          }
